### ISSUE TITLE
KeyError: 3932190

### ISSUE THREAD

**Issue by jpmaligne** [allan-simon/mock-amqp-server#3]
```
KeyError: 3932190
3932190
0x3c001e
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 732, in _read_ready
    self._protocol.data_received(data)
  File "/home/jp/workspace/mock-amqp-server/service/protocol.py", line 102, in data_received
    frame_value = read_frame(self._buffer)
  File "/home/jp/workspace/mock-amqp-server/service/frame.py", line 52, in read_frame
    payload,
  File "/home/jp/workspace/mock-amqp-server/service/method.py", line 43, in __init__
    decode_method = _ID_TO_METHOD[method_id]
KeyError: 3932190

```

**Comment by allan-simon** [comment]
ok it seems pika use the method "cancel" when disconnecting, which I didn't implemented yet, on it.
