### ISSUE TITLE
Key Error on nack : 3932280

### ISSUE THREAD

**Issue by jpmaligne** [allan-simon/mock-amqp-server#9]
I get an error when calling Pika method channel.basic_nack() passing a delivry_tag as parameter.

Here is the stack trace : 

```
rabbitmq_1            | 3932280
rabbitmq_1            | Method id: 0x3c0078
rabbitmq_1            | Traceback (most recent call last):
rabbitmq_1            |   File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
rabbitmq_1            |     self._callback(*self._args)
rabbitmq_1            |   File "/usr/lib/python3.6/asyncio/selector_events.py", line 730, in _read_ready
rabbitmq_1            |     self._protocol.data_received(data)
rabbitmq_1            |   File "/service/protocol.py", line 103, in data_received
rabbitmq_1            |     frame_value = read_frame(self._buffer)
rabbitmq_1            |   File "/service/frame.py", line 52, in read_frame
rabbitmq_1            |     payload,
rabbitmq_1            |   File "/service/method.py", line 44, in __init__
rabbitmq_1            |     decode_method = _ID_TO_METHOD[method_id]
rabbitmq_1            | KeyError: 3932280
```

It causes the service to shut down du to too many missied heartbeats in the last 10 seconds

**Comment by allan-simon** [comment]
it's because the nack method is not implemented :)
